#!/usr/bin/env python3
# Usage:
#   python tools/prepare_charades_sta.py \
#     --input_txt /data/Raw/Charades-STA/raw/charades_sta_test.txt \
#     --video_root /data/Raw/Charades-Video \
#     --output_json /data/MarkIt/test.json \
#     --summary_json /data/MarkIt/test.summary.json \
#     --nouns_json /data/MarkIt/nouns_qwen.json \
#     --strict_videos
#
# Docker Compose example:
#   docker compose run --rm markit bash -lc '
#   python tools/prepare_charades_sta.py \
#     --input_txt /data/Raw/Charades-STA/charades_sta_test.txt \
#     --video_root "$RAW_VIDEO_ROOT" \
#     --output_json "$TEST_PATH" \
#     --summary_json /data/MarkIt/test.summary.json \
#     --strict_videos'
#
# Notes:
#   - The default noun extractor is a lightweight heuristic for bootstrapping.
#   - For paper-parity nouns, pass --nouns_json generated by a Qwen noun extractor.
#   - If --video_root is omitted, duration falls back to each video's max annotation end time.
from __future__ import annotations

import argparse
import json
import math
import re
from collections import defaultdict
from pathlib import Path
from typing import Any


STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "being",
    "by",
    "for",
    "from",
    "his",
    "her",
    "in",
    "inside",
    "into",
    "is",
    "it",
    "its",
    "near",
    "of",
    "off",
    "on",
    "onto",
    "or",
    "out",
    "outside",
    "over",
    "their",
    "the",
    "then",
    "there",
    "through",
    "to",
    "under",
    "up",
    "with",
}

ACTION_WORDS = {
    "begin",
    "begins",
    "clean",
    "cleaning",
    "cleans",
    "close",
    "closed",
    "closes",
    "closing",
    "drink",
    "drinking",
    "drinks",
    "eat",
    "eating",
    "enter",
    "enters",
    "exit",
    "exits",
    "flip",
    "flipped",
    "flipping",
    "get",
    "gets",
    "getting",
    "go",
    "goes",
    "going",
    "grab",
    "grabs",
    "grabbing",
    "hold",
    "holding",
    "holds",
    "leave",
    "leaves",
    "leaving",
    "look",
    "looking",
    "looks",
    "make",
    "makes",
    "making",
    "move",
    "moves",
    "moving",
    "open",
    "opened",
    "opening",
    "opens",
    "pick",
    "picks",
    "picking",
    "place",
    "places",
    "placing",
    "play",
    "playing",
    "plays",
    "pour",
    "pouring",
    "pours",
    "put",
    "puts",
    "putting",
    "read",
    "reading",
    "run",
    "running",
    "set",
    "sets",
    "setting",
    "sit",
    "sits",
    "sitting",
    "stand",
    "standing",
    "start",
    "starts",
    "take",
    "takes",
    "taking",
    "throw",
    "throwing",
    "turn",
    "turned",
    "turning",
    "turns",
    "use",
    "uses",
    "using",
    "walk",
    "walked",
    "walking",
    "walks",
    "watch",
    "watching",
}


def normalize_text(text: str) -> str:
    return " ".join(str(text).strip().split())


def normalize_number(value: float) -> int | float:
    if math.isfinite(value) and float(value).is_integer():
        return int(value)
    return round(float(value), 4)


def parse_charades_sta_line(line: str, line_number: int) -> dict[str, Any] | None:
    raw = line.strip()
    if not raw or raw.startswith("#"):
        return None
    if "##" not in raw:
        raise ValueError(f"Line {line_number}: expected '<video> <start> <end>##<query>'")

    meta, query = raw.split("##", 1)
    parts = meta.split()
    if len(parts) != 3:
        raise ValueError(f"Line {line_number}: expected three metadata fields before ##")

    video_id, start_text, end_text = parts
    start_time = float(start_text)
    end_time = float(end_text)
    if end_time < start_time:
        raise ValueError(f"Line {line_number}: end_time < start_time")

    return {
        "video_id": video_id,
        "start_time": start_time,
        "end_time": end_time,
        "query": normalize_text(query),
    }


def load_charades_sta(path: Path) -> list[dict[str, Any]]:
    records = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        item = parse_charades_sta_line(line, line_number)
        if item is not None:
            records.append(item)
    return records


def import_cv2():
    try:
        import cv2  # type: ignore
    except ImportError:
        return None
    return cv2


def probe_video_duration(video_path: Path) -> float | None:
    cv2 = import_cv2()
    if cv2 is None or not video_path.exists():
        return None

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        cap.release()
        return None
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)
    frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    cap.release()
    if fps <= 0 or frames <= 0:
        return None
    return frames / fps


def load_noun_overrides(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {}
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise ValueError("--nouns_json must contain a JSON object")
    return payload


def coerce_nouns(value: Any, max_nouns: int) -> dict[str, str]:
    if isinstance(value, dict):
        items = sorted(value.items(), key=lambda kv: int(kv[0]) if str(kv[0]).isdigit() else str(kv[0]))
        nouns = [str(noun).strip() for _, noun in items if str(noun).strip()]
    elif isinstance(value, list):
        nouns = [str(noun).strip() for noun in value if str(noun).strip()]
    elif isinstance(value, str) and value.strip():
        nouns = [value.strip()]
    else:
        nouns = []

    if max_nouns > 0:
        nouns = nouns[:max_nouns]
    return {str(idx): noun for idx, noun in enumerate(nouns, start=1)}


def heuristic_nouns(query: str, max_nouns: int) -> dict[str, str]:
    tokens = re.findall(r"[a-z0-9]+(?:'[a-z0-9]+)?", query.lower())
    chunks: list[list[str]] = []
    current: list[str] = []

    for token in tokens:
        if token in STOPWORDS or token in ACTION_WORDS:
            if current:
                chunks.append(current)
                current = []
            continue
        current.append(token)
    if current:
        chunks.append(current)

    candidates: list[str] = []
    for chunk in chunks:
        if not chunk:
            continue
        if len(chunk) == 1:
            candidates.append(chunk[0])
        elif len(chunk) == 2:
            candidates.append(" ".join(chunk))
        else:
            candidates.append(" ".join(chunk[-2:]))

    if "person" in tokens and "person" not in candidates:
        candidates.insert(0, "person")

    unique: list[str] = []
    seen = set()
    for noun in candidates:
        noun = noun.strip()
        if len(noun) <= 1 or noun in seen:
            continue
        seen.add(noun)
        unique.append(noun)
        if max_nouns > 0 and len(unique) >= max_nouns:
            break

    return {str(idx): noun for idx, noun in enumerate(unique, start=1)}


def build_records(args: argparse.Namespace) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    raw_records = load_charades_sta(Path(args.input_txt))
    if args.max_records > 0:
        raw_records = raw_records[: args.max_records]

    max_end_by_video: dict[str, float] = defaultdict(float)
    for item in raw_records:
        max_end_by_video[item["video_id"]] = max(max_end_by_video[item["video_id"]], item["end_time"])

    duration_cache: dict[str, float] = {}
    missing_videos: list[str] = []
    video_root = Path(args.video_root) if args.video_root else None
    for video_id in sorted(max_end_by_video):
        duration = None
        if video_root is not None:
            video_path = video_root / f"{video_id}{args.video_ext}"
            duration = probe_video_duration(video_path)
            if duration is None:
                missing_videos.append(str(video_path))
        duration_cache[video_id] = float(duration if duration is not None else max_end_by_video[video_id])

    if args.strict_videos and missing_videos:
        preview = "\n".join(missing_videos[:10])
        raise FileNotFoundError(f"Missing or unreadable videos, first entries:\n{preview}")

    noun_overrides = load_noun_overrides(Path(args.nouns_json) if args.nouns_json else None)
    per_video_counts: dict[str, int] = defaultdict(int)
    converted: list[dict[str, Any]] = []

    for item in raw_records:
        video_id = item["video_id"]
        per_video_counts[video_id] += 1
        record_id = f"{video_id}_{per_video_counts[video_id]}"
        video_name = f"{video_id}{args.video_ext}"

        if record_id in noun_overrides:
            nouns = coerce_nouns(noun_overrides[record_id], args.max_nouns)
        elif item["query"] in noun_overrides:
            nouns = coerce_nouns(noun_overrides[item["query"]], args.max_nouns)
        elif args.noun_mode == "heuristic":
            nouns = heuristic_nouns(item["query"], args.max_nouns)
        else:
            nouns = {}

        converted.append(
            {
                "id": record_id,
                "video": video_name,
                "query": item["query"],
                "start_time": normalize_number(item["start_time"]),
                "end_time": normalize_number(item["end_time"]),
                "duration": normalize_number(duration_cache[video_id]),
                "nouns": nouns,
            }
        )

    summary = {
        "input_txt": str(args.input_txt),
        "output_json": str(args.output_json),
        "video_root": args.video_root,
        "video_ext": args.video_ext,
        "num_records": len(converted),
        "num_videos": len(per_video_counts),
        "noun_mode": args.noun_mode,
        "missing_or_unreadable_videos": len(missing_videos),
        "duration_source": "video_probe_when_available_else_max_annotation_end",
    }
    return converted, summary


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert Charades-STA text annotations to MarkIt test.json format."
    )
    parser.add_argument("--input_txt", required=True, help="Path to charades_sta_test.txt")
    parser.add_argument("--output_json", required=True, help="Output MarkIt test JSON")
    parser.add_argument("--summary_json", help="Optional summary JSON path")
    parser.add_argument("--video_root", help="Directory containing Charades videos")
    parser.add_argument("--video_ext", default=".mp4", help="Video extension, default: .mp4")
    parser.add_argument("--strict_videos", action="store_true", help="Fail if any video is missing/unreadable")
    parser.add_argument("--max_records", type=int, default=-1, help="Optional record limit for smoke tests")
    parser.add_argument(
        "--noun_mode",
        choices=["none", "heuristic"],
        default="heuristic",
        help="How to populate nouns when --nouns_json has no entry",
    )
    parser.add_argument("--nouns_json", help="Optional JSON mapping record id or query text to nouns")
    parser.add_argument("--max_nouns", type=int, default=3)
    args = parser.parse_args()

    records, summary = build_records(args)
    write_json(Path(args.output_json), records)
    if args.summary_json:
        write_json(Path(args.summary_json), summary)

    print(f"wrote {len(records)} records to {args.output_json}")
    print(f"videos: {summary['num_videos']}; missing/unreadable: {summary['missing_or_unreadable_videos']}")
    if args.noun_mode == "heuristic":
        print("note: heuristic nouns are a runnable baseline, not the paper's Qwen noun extractor")


if __name__ == "__main__":
    main()
